# Generated by Django 6.0.4 on 2026-05-13 00:54

from django.db import migrations
from django.contrib.auth.models import Group

def create_user_groups(apps, schema_editor):
    Group.objects.get_or_create(name='Administrador')
    Group.objects.get_or_create(name='Empleado')

def remove_user_groups(apps, schema_editor):
    Group.objects.filter(name__in=['Administrador', 'Empleado']).delete()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_user_groups, reverse_code=remove_user_groups),
    ]
